apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-controler-ds-wildcard-cert
  namespace: ingress-nginx-ds
spec:
  secretName: letsencrypt-secret-prod
  issuerRef:
    name: letsencrypt-nginx-controller-ds-issuer
    kind: Issuer
  commonName: "*.dancingspoon.net"
  dnsNames:
  - "*.dancingspoon.net"
  - "dancingspoon.net"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    size: 2048
