apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-cluster-utr-app-prod-k8s0
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/app-of-apps
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-app-prod-k8s0.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
