s3-storage:
  minio-tenant:
    tenant:
      name: s3-storage
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 10Gi
      buckets:
        - name: backup
          objectLock: false
          region: us-east-1
    ingress:
      api:
        enabled: true
        ingressClassName: "nginx-utr"
        host: s3.k3s1.ujstor.com
      console:
        enabled: true
        ingressClassName: "nginx-utr"
        host: s3.console.k3s1.ujstor.com
