notes-flask:
  ingress:
    hosts:
      - host: notes-flask.astipan.com
        paths:
          - path: /
            pathType: Prefix
    tls:
     - secretName: notes-flask-prod-tls
       hosts:
         - notes-flask.astipan.com
