apiVersion: v2
name: streamlit-wh
description: Ujstor's streamlit-wh Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.1"

dependencies:
- name: streamlit-wh
  version: 1.0.0
  repository: "oci://harbor.k3s0.ujstor.com/helm"
