apiVersion: v2
name: portfolio
description: Portfolio Helm chartr
type: application
version: 1.1.0
appVersion: "1.2.3"

dependencies:
- name: portfolio
  version: 1.1.0
  repository: "oci://harbor.k3s0.ujstor.com/helm"
