wp-ds:
  wordpress:
    wordpressUsername: tena
    wordpressEmail: tena.tomasevic@gmail.com
    wordpressFirstName: Tena
    wordpressLastName: Tomasevic
    wordpressBlogName: Dancing Spoon
    wordpressScheme: https

    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: "nginx"
      hostname: dancingspoon.net
      path: /
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
        nginx.ingress.kubernetes.io/client-body-buffer-size: "50m"
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
      tls: true

    persistence:
      size: 5Gi
