apiVersion: v2
name: github-readme-stats
description: A Helm chart for Kubernetes
type: application
version: 1.1.0
appVersion: "1.1.0"

dependencies:
- name: github-readme-stats
  version: 1.1.0
  repository: "oci://harbor.k3s0.ujstor.com/helm"
