s3-storage:
  minio-tenant:
    tenant:
      name: s3-storage
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 50Gi
    ingress:
      api:
        enabled: true
        tls: 
          - secretName: minio-api-tls
            hosts:
              - s3.harbor.k3s1.ujstor.com
        host: s3.harbor.k3s1.ujstor.com
      console:
        enabled: true
        tls: 
          - secretName: minio-console-tls
            hosts:
              - s3.harbor.console.k3s1.ujstor.com
        host: s3.harbor.console.k3s1.ujstor.com
