s3-storage:
  minio-tenant:
    tenant:
      name: s3-storage
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 50Gi
    ingress:
      api:
        ingressClassName: "nginx-utr"
        enabled: true
        host: s3.harbor.k3s1.ujstor.com
      console:
        ingressClassName: "nginx-utr"
        enabled: true
        host: s3.harbor.console.k3s1.ujstor.com
