apiVersion: v2
name: Kyverno
description: Kyverno Helm chart by Ujstor
type: application
version: 1.0.0
appVersion: "1.13.4"

dependencies:
- name: ingress-nginx
  version: 1.0.0
  repository: "oci://harbor.k3s0.ujstor.com/helm"
