apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx-controller-utr-issuer
  namespace: ingress-nginx-utr
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-key
            name: nginx-controller-utr-issuer
