apiVersion: v2
name: external-secrets
description: External-Secrets Helm chart configured by Ujstor
type: application
version: 1.1.1
appVersion: "v0.14.4"

dependencies:
- name: external-secrets
  version: 1.1.1
  repository: "oci://harbor.k3s0.ujstor.com/helm"
