apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-metallb-config-k3s1
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook-dependency: system-metallb-operator
spec:
  destination:
    namespace: metallb
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helmsystem/metallb-config
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/apps-k3s1.git
    targetRevision: main
    helm:
      version: v3
      releaseName: metallb-config
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
