apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cert-manager-k3s1
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-dependency: system-ingress-nginx
spec:
  destination:
    namespace: cert-manager
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/system/cert-manager
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-app-prod-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
