apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cluster-issuer-k3s1
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/hook-dependency: system-cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/system/cluster-issuer
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/apps-k3s1.git
    targetRevision: main
    helm:
      version: v3
      releaseName: cluster-issuer
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
