apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-kyverno-utr-app-prod-k8s0
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  destination:
    namespace: kyverno
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/system/kyverno
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-app-prod-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: kyverno
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
