apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-portfolio-k3s1
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  destination:
    namespace: portfolio
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/apps/portfolio
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-app-prod-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: portfolio
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
