apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-probit-api-k3s1
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  destination:
    namespace: probit
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/apps/probit-api
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-app-prod-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: probit
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
