apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-todo-django-k3s1
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  destination:
    namespace: django-todo
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/apps/todo-django
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/apps-k3s1.git
    targetRevision: main
    helm:
      version: v3
      releaseName: django-todo
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
