apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-plausible-analytics-k3s1
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    "argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"
spec:
  destination:
    namespace: plausible-analytics
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/apps/plausible-analytics
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-app-prod-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: plausible-analytics
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: plausible-analytics
    jsonPointers:
    - /data
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
