apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-s3-backup-utr-app-prod-k8s0
  namespace: gitops
  annotations:
   argocd.argoproj.io/sync-wave: "19"
spec:
  destination:
    namespace: s3-storage
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: gitops/helm/apps/s3-storage
    repoURL: https://gitlab.k3s0.ujstor.com/clusters/customer-ujstor/utr-app-prod-k8s0.git
    targetRevision: main
    helm:
      version: v3
      releaseName: s3-storage
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
