---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-db
  namespace: {{ .Release.Namespace }}
spec:
  rootPasswordSecretKeyRef:
    name: wordpress-db-secret
    key: mariadb-password
  image: docker-registry1.mariadb.com/library/mariadb:11.7
  port: 3306
  volumeClaimTemplate:
    resources:
      requests:
        storage: 5Gi
    accessModes:
      - ReadWriteOnce
  service:
    type: ClusterIP
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: wordpress-db
  namespace: {{ .Release.Namespace }}
spec:
  mariaDbRef:
    name: wordpress-db
    namespace: {{ .Release.Namespace }}
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress-user
  namespace: {{ .Release.Namespace }}
spec:
  mariaDbRef:
    name: wordpress-db
    namespace: {{ .Release.Namespace }}
  passwordSecretKeyRef:
    name: wordpress-db-secret
    key: mariadb-password
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress-grant
  namespace: {{ .Release.Namespace }}
spec:
  mariaDbRef:
    name: wordpress-db
    namespace: {{ .Release.Namespace }}
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
    - "CREATE"
    - "DROP"
    - "INDEX"
    - "ALTER"
    - "CREATE TEMPORARY TABLES"
  database: wordpress-db
  username: wordpress-user
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: {{ .Release.Namespace }}
stringData:
  mariadb-password: "wordpress"
